HEADER_DEFINITION = 0
HEADER_NAMED_ALIASES = 1
HEADER_READINGS = 2
HEADER_SEE_ALSO = 3
HEADER_BLOCK_INFO = 4
HEADER_SUBBLOCK_INFO = 5
HEADER_SCRIPTS_BLOCKS = 6
HEADER_UNICODE_GENERAL = 7
HEADER_CASING = 8
HEADER_NORMALISATION = 9
HEADER_NUMERIC = 10
HEADER_LANGUAGE_USAGE = 11
HEADER_VARIANTS = 12
HEADER_GRADES_FREQUENCIES = 13
HEADER_TOTAL_STROKES = 14
HEADER_RADICAL_STROKES = 15
HEADER_INPUT = 16
HEADER_ENCODING = 17
HEADER_UNICODE_LAYOUT = 18
HEADER_INDICES = 19
HEADER_PHONETIC_INDICES = 20
HEADER_ADOBE = 21
HEADER_FIXME = None  # TODO!!!

DHeaders = {
    'Definition': 'HEADER_DEFINITION',
    'Numeric': 'HEADER_NUMERIC',
    'Readings': 'HEADER_READINGS',
    'Language Usage': 'HEADER_LANGUAGE_USAGE',
    'Variants': 'HEADER_VARIANTS',
    'Grades/Frequencies': 'HEADER_GRADES_FREQUENCIES',
    'Total Strokes': 'HEADER_TOTAL_STROKES',
    'Radical/Additional Strokes': 'HEADER_RADICAL_STROKES',
    'Input': 'HEADER_INPUT',
    'Encoding': 'HEADER_ENCODING',
    'Indices': 'HEADER_INDICES',
    'Phonetic Indices': 'HEADER_PHONETIC_INDICES',
    'Adobe': 'HEADER_ADOBE',
    None: 'HEADER_FIXME'
}
