HEADER_DEFINITION = 0
HEADER_NUMERIC = 1
HEADER_READINGS = 2
HEADER_LANGUAGE_USAGE = 3
HEADER_VARIANTS = 4
HEADER_GRADES_FREQUENCIES = 5
HEADER_TOTAL_STROKES = 6
HEADER_RADICAL_STROKES = 7
HEADER_INPUT = 8
HEADER_ENCODING = 9
HEADER_INDICES = 10
HEADER_PHONETIC_INDICES = 11
HEADER_ADOBE = 12
HEADER_FIXME = None  # TODO!!!

DHeaders = {
    'Definition': 'HEADER_DEFINITION',
    'Numeric': 'HEADER_NUMERIC',
    'Readings': 'HEADER_READINGS',
    'Language Usage': 'HEADER_LANGUAGE_USAGE',
    'Variants': 'HEADER_VARIANTS',
    'Grades/Frequencies': 'HEADER_GRADES_FREQUENCIES',
    'Total Strokes': 'HEADER_TOTAL_STROKES',
    'Radical/Additional Strokes': 'HEADER_RADICAL_STROKES',
    'Input': 'HEADER_INPUT',
    'Encoding': 'HEADER_ENCODING',
    'Indices': 'HEADER_INDICES',
    'Phonetic Indices': 'HEADER_PHONETIC_INDICES',
    'Adobe': 'HEADER_ADOBE',
    None: 'HEADER_FIXME'
}
