DReadablePropertyKeys = {
    'ccdict.cantonese': 'Cantonese Readings',
    'ccdict.english': 'English Definition',
    'ccdict.hakka': 'Hakka Readings',
    'ccdict.mandarin': 'Mandarin Readings',
    'ccdict.r/s': '{{FIXME}} Radicals and Additional Strokes',
    'kanjidic.dicref_crowley': '',
    'kanjidic.dicref_gakken': '',
    'kanjidic.dicref_halpern_kkld': '',
    'kanjidic.dicref_halpern_njecd': '',
    'kanjidic.dicref_heisig': '',
    'kanjidic.dicref_henshall': '',
    'kanjidic.dicref_henshall3': '',
    'kanjidic.dicref_jf_cards': '',
    'kanjidic.dicref_kanji_in_context': '',
    'kanjidic.dicref_kodansha_compact': '',
    'kanjidic.dicref_maniette': '',
    'kanjidic.dicref_moro': '',
    'kanjidic.dicref_nelson_c': '',
    'kanjidic.dicref_nelson_n': '',
    'kanjidic.dicref_oneill_kk': '',
    'kanjidic.dicref_oneill_names': '',
    'kanjidic.dicref_sakade': '',
    'kanjidic.dicref_sh_kk': '',
    'kanjidic.dicref_tutt_cards': '',
    'kanjidic.freq': 'Japanese Frequency',
    'kanjidic.grade': 'Japanese Grade',
    'kanjidic.jlpt': 'Japanese JLPT level',
    'kanjidic.meaning': 'English Definition for Japanese',
    'kanjidic.meaning_es': 'Spanish Definition for Japanese',
    'kanjidic.meaning_fr': 'French Definition for Japanese',
    'kanjidic.meaning_pt': 'Portuguese Definition for Japanese',
    'kanjidic.querycode_deroo': '',
    'kanjidic.rad_classical': '',
    'kanjidic.rad_name': '',
    'kanjidic.rad_nelson_c': '',
    'kanjidic.reading_ja_kun': 'Kun Readings',
    'kanjidic.reading_ja_on': 'On Readings',
    'kanjidic.reading_korean_h': 'Korean Hangul Readings',
    'kanjidic.reading_korean_r': 'Korean Romanised Readings',
    'kanjidic.reading_nanori': 'Japanese Nanori Readings',
    'kanjidic.reading_pinyin': 'Mandarin Readings',
    'kanjidic.stroke_count': 'Japanese Number of Strokes',
    'nameslist.see also': '',
    'nameslist.subblock see also': '',
    'unicodedata.age': 'Unicode Age',
    'unicodedata.also called': 'Also Called',
    'unicodedata.arabic shaping group': 'Arabic Shaping Group',
    'unicodedata.arabic shaping type': 'Arabic Shaping Type',
    'unicodedata.bidirectional category': 'Bidirectional Category',
    'unicodedata.block': 'General Block',
    'unicodedata.canonical combining classes': '',
    'unicodedata.case folding status': '',
    'unicodedata.comments': '',
    'unicodedata.conscript blocks': '',
    'unicodedata.conscript name': '',
    'unicodedata.core properties': '',
    'unicodedata.decimal digit value': '',
    'unicodedata.digit value': '',
    'unicodedata.east asian width': '',
    'unicodedata.fc nfkc closure': '',
    'unicodedata.formally also called': '',
    'unicodedata.general category': '',
    'unicodedata.grapheme break': '',
    'unicodedata.joining type': '',
    'unicodedata.line break': '',
    'unicodedata.name': '',
    'unicodedata.named aliases': '',
    'unicodedata.numeric value': '',
    'unicodedata.property list': '',
    'unicodedata.script': '',
    'unicodedata.sentence break': '',
    'unicodedata.technical notice': '',
    'unicodedata.unicode 1.0 name': '',
    'unicodedata.word break': '',
    'unihan.accountingnumeric': '',
    'unihan.cantonese': '',
    'unihan.cheungbauerindex': '',
    'unihan.cihait': '',
    'unihan.cowles': '',
    'unihan.daejaweon': '',
    'unihan.definition': 'English Definition',
    'unihan.fennindex': '',
    'unihan.frequency': 'Chinese Frequency',
    'unihan.gradelevel': 'Chinese Grade Level',
    'unihan.gsr': '',
    'unihan.hangul': 'Korean Hangul Readings',
    'unihan.hanyu': '',
    'unihan.hanyupinlu': '',
    'unihan.hanyupinyin': 'Mandarin Hanyu Pinyin', # ???
    'unihan.hkglyph': '',
    'unihan.iicore': '',
    'unihan.japanesekun': 'Japanese Kun',
    'unihan.japaneseon': 'Japanese On',
    'unihan.kangxi': 'Kangxi Radical',
    'unihan.karlgren': '',
    'unihan.korean': 'Korean Romanised Readings',
    'unihan.lau': '',
    'unihan.mandarin': 'Mandarin Readings',
    'unihan.matthews': '',
    'unihan.meyerwempe': '',
    'unihan.morohashi': '',
    'unihan.nelson': '',
    'unihan.othernumeric': 'Other Numeric Value',
    'unihan.primarynumeric': 'Primary Numeric Value',
    'unihan.rsjapanese': 'Japanese Radicals and Additional Strokes',
    'unihan.rskangxi': 'Kangxi Radicals and Additional Strokes',
    'unihan.rskanwa': 'Kanwa Radicals and Additional Strokes',
    'unihan.rskorean': 'Korean Radicals and Additional Strokes',
    'unihan.rsunicode': 'Unicode Radicals and Additional Strokes',
    'unihan.sbgy': '',
    'unihan.tang': 'Tang Dynasty Chinese Readings',
    'unihan.totalstrokes': 'Total Strokes',
    'unihan.vietnamese': 'Vietnamese Readings',
    'unihan.xhc1983': '',
}



[('ccdict', u'big5'),
 ('ccdict', u'cangjie'),
 ('ccdict', u'cantonese'),
 ('ccdict', u'cns11643'),
 ('ccdict', u'english'),
 ('ccdict', u'fourcorner'),
 ('ccdict', u'gb'),
 ('ccdict', u'hakka'),
 ('ccdict', u'mandarin'),
 ('ccdict', u'r/s'),
 ('ccdict', u'totalstrokes'),
 ('ccdict', u'utf8'),
 ('hanzi variants', 'abbreviated form'),
 ('hanzi variants', 'antonym'),
 ('hanzi variants', 'archaic form'),
 ('hanzi variants', 'archaic variant'),
 ('hanzi variants', 'chinese classifier'),
 ('hanzi variants', 'chinesetraditional'),
 ('hanzi variants', 'correct form'),
 ('hanzi variants', 'erhua variant'),
 ('hanzi variants', 'erroneous form'),
 ('hanzi variants', 'japanese variant'),
 ('hanzi variants', 'japanesesimplified'),
 ('hanzi variants', 'less common variant'),
 ('hanzi variants', 'modern form'),
 ('hanzi variants', 'modern variant'),
 ('hanzi variants', 'more common variant'),
 ('hanzi variants', 'non-erhua variant'),
 ('hanzi variants', 'non-japanese variant'),
 ('hanzi variants', 'non-prc variant'),
 ('hanzi variants', 'obscure variant'),
 ('hanzi variants', 'other variant'),
 ('hanzi variants', 'popular variant'),
 ('hanzi variants', 'prc variant'),
 ('hanzi variants', 'same as'),
 ('hanzi variants', 'see also'),
 ('hanzi variants', 'unabbreviated form'),
 ('hanzi variants', 'variant of'),
 ('hanzi variants', 'words which can use classifier'),
 ('kanjidic', u'crossref_deroo'),
 ('kanjidic', u'crossref_jis208'),
 ('kanjidic', u'crossref_jis212'),
 ('kanjidic', u'crossref_jis213'),
 ('kanjidic', u'crossref_nelson_c'),
 ('kanjidic', u'crossref_njecd'),
 ('kanjidic', u'crossref_oneill'),
 ('kanjidic', u'crossref_s_h'),
 ('kanjidic', u'crossref_ucs'),
 ('kanjidic', u'dicref_busy_people'),
 ('kanjidic', u'dicref_crowley'),
 ('kanjidic', u'dicref_gakken'),
 ('kanjidic', u'dicref_halpern_kkld'),
 ('kanjidic', u'dicref_halpern_njecd'),
 ('kanjidic', u'dicref_heisig'),
 ('kanjidic', u'dicref_henshall'),
 ('kanjidic', u'dicref_henshall3'),
 ('kanjidic', u'dicref_jf_cards'),
 ('kanjidic', u'dicref_kanji_in_context'),
 ('kanjidic', u'dicref_kodansha_compact'),
 ('kanjidic', u'dicref_maniette'),
 ('kanjidic', u'dicref_moro'),
 ('kanjidic', u'dicref_nelson_c'),
 ('kanjidic', u'dicref_nelson_n'),
 ('kanjidic', u'dicref_oneill_kk'),
 ('kanjidic', u'dicref_oneill_names'),
 ('kanjidic', u'dicref_sakade'),
 ('kanjidic', u'dicref_sh_kk'),
 ('kanjidic', u'dicref_tutt_cards'),
 ('kanjidic', u'freq'),
 ('kanjidic', u'grade'),
 ('kanjidic', u'jlpt'),
 ('kanjidic', u'meaning'),
 ('kanjidic', u'meaning_es'),
 ('kanjidic', u'meaning_fr'),
 ('kanjidic', u'meaning_pt'),
 ('kanjidic', u'querycode_deroo'),
 ('kanjidic', u'querycode_four_corner'),
 ('kanjidic', u'querycode_sh_desc'),
 ('kanjidic', u'rad_classical'),
 ('kanjidic', u'rad_name'),
 ('kanjidic', u'rad_nelson_c'),
 ('kanjidic', u'reading_ja_kun'),
 ('kanjidic', u'reading_ja_on'),
 ('kanjidic', u'reading_korean_h'),
 ('kanjidic', u'reading_korean_r'),
 ('kanjidic', u'reading_nanori'),
 ('kanjidic', u'reading_pinyin'),
 ('kanjidic', u'stroke_count'),
 ('nameslist', u'also called'),
 ('nameslist', u'block description'),
 ('nameslist', u'block name'),
 ('nameslist', u'comments'),
 ('nameslist', u'formally also called'),
 ('nameslist', u'has separator'),
 ('nameslist', u'see also'),
 ('nameslist', u'subblock heading'),
 ('nameslist', u'subblock see also'),
 ('nameslist', u'subblock technical notice'),
 ('nameslist', u'technical notice'),
 ('unicodedata', u'age'),
 ('unicodedata', u'also called'),
 ('unicodedata', u'arabic shaping group'),
 ('unicodedata', u'arabic shaping type'),
 ('unicodedata', u'bidi mirroring'),
 ('unicodedata', u'bidirectional category'),
 ('unicodedata', u'block'),
 ('unicodedata', u'block description'),
 ('unicodedata', u'block name'),
 ('unicodedata', u'canonical combining classes'),
 ('unicodedata', u'case folding'),
 ('unicodedata', u'case folding status'),
 ('unicodedata', u'changes when nfkc casefolded'),
 ('unicodedata', u'comments'),
 ('unicodedata', u'compatibility mapping'),
 ('unicodedata', u'composition exclusions'),
 ('unicodedata', u'conscript blocks'),
 ('unicodedata', u'conscript name'),
 ('unicodedata', u'core properties'),
 ('unicodedata', u'decimal digit value'),
 ('unicodedata', u'decomposed form'),
 ('unicodedata', u'digit value'),
 ('unicodedata', u'east asian width'),
 ('unicodedata', u'expands on nfc'),
 ('unicodedata', u'expands on nfd'),
 ('unicodedata', u'expands on nfkc'),
 ('unicodedata', u'expands on nfkd'),
 ('unicodedata', u'fc nfkc closure'),
 ('unicodedata', u'formally also called'),
 ('unicodedata', u'full composition exclusion'),
 ('unicodedata', u'general category'),
 ('unicodedata', u'grapheme break'),
 ('unicodedata', u'joining type'),
 ('unicodedata', u'line break'),
 ('unicodedata', u'lowercase'),
 ('unicodedata', u'mirrored'),
 ('unicodedata', u'name'),
 ('unicodedata', u'named aliases'),
 ('unicodedata', u'nfc quick check'),
 ('unicodedata', u'nfd quick check'),
 ('unicodedata', u'nfkc casefold'),
 ('unicodedata', u'nfkc quick check'),
 ('unicodedata', u'nfkd quick check'),
 ('unicodedata', u'normalization corrections corrected'),
 ('unicodedata', u'normalization corrections errors'),
 ('unicodedata', u'numeric value'),
 ('unicodedata', u'property list'),
 ('unicodedata', u'script'),
 ('unicodedata', u'see also'),
 ('unicodedata', u'sentence break'),
 ('unicodedata', u'special casing condition list'),
 ('unicodedata', u'special casing lower'),
 ('unicodedata', u'special casing title'),
 ('unicodedata', u'special casing upper'),
 ('unicodedata', u'subblock heading'),
 ('unicodedata', u'subblock see also'),
 ('unicodedata', u'subblock technical notice'),
 ('unicodedata', u'technical notice'),
 ('unicodedata', u'titlecase'),
 ('unicodedata', u'unicode 1.0 name'),
 ('unicodedata', u'uppercase'),
 ('unicodedata', u'word break'),
 ('unihan', u'accountingnumeric'),
 ('unihan', u'bigfive'),
 ('unihan', u'cangjie'),
 ('unihan', u'cantonese'),
 ('unihan', u'cccii'),
 ('unihan', u'cheungbauer'),
 ('unihan', u'cheungbauerindex'),
 ('unihan', u'cihait'),
 ('unihan', u'cns1986'),
 ('unihan', u'cns1992'),
 ('unihan', u'compatibilityvariant'),
 ('unihan', u'cowles'),
 ('unihan', u'daejaweon'),
 ('unihan', u'definition'),
 ('unihan', u'eacc'),
 ('unihan', u'fenn'),
 ('unihan', u'fennindex'),
 ('unihan', u'fourcornercode'),
 ('unihan', u'frequency'),
 ('unihan', u'gb0'),
 ('unihan', u'gb1'),
 ('unihan', u'gb3'),
 ('unihan', u'gb5'),
 ('unihan', u'gb7'),
 ('unihan', u'gb8'),
 ('unihan', u'gradelevel'),
 ('unihan', u'gsr'),
 ('unihan', u'hangul'),
 ('unihan', u'hanyu'),
 ('unihan', u'hanyupinlu'),
 ('unihan', u'hanyupinyin'),
 ('unihan', u'hdzradbreak'),
 ('unihan', u'hkglyph'),
 ('unihan', u'hkscs'),
 ('unihan', u'ibmjapan'),
 ('unihan', u'iicore'),
 ('unihan', u'irg_gsource'),
 ('unihan', u'irg_hsource'),
 ('unihan', u'irg_jsource'),
 ('unihan', u'irg_kpsource'),
 ('unihan', u'irg_ksource'),
 ('unihan', u'irg_msource'),
 ('unihan', u'irg_tsource'),
 ('unihan', u'irg_usource'),
 ('unihan', u'irg_vsource'),
 ('unihan', u'irgdaejaweon'),
 ('unihan', u'irgdaikanwaziten'),
 ('unihan', u'irghanyudazidian'),
 ('unihan', u'irgkangxi'),
 ('unihan', u'japanesekun'),
 ('unihan', u'japaneseon'),
 ('unihan', u'jis0'),
 ('unihan', u'jis0213'),
 ('unihan', u'jis1'),
 ('unihan', u'kangxi'),
 ('unihan', u'karlgren'),
 ('unihan', u'korean'),
 ('unihan', u'kps0'),
 ('unihan', u'kps1'),
 ('unihan', u'ksc0'),
 ('unihan', u'ksc1'),
 ('unihan', u'lau'),
 ('unihan', u'mainlandtelegraph'),
 ('unihan', u'mandarin'),
 ('unihan', u'matthews'),
 ('unihan', u'meyerwempe'),
 ('unihan', u'morohashi'),
 ('unihan', u'nelson'),
 ('unihan', u'othernumeric'),
 ('unihan', u'phonetic'),
 ('unihan', u'primarynumeric'),
 ('unihan', u'pseudogb1'),
 ('unihan', u'rsadobe_japan1_6'),
 ('unihan', u'rsjapanese'),
 ('unihan', u'rskangxi'),
 ('unihan', u'rskanwa'),
 ('unihan', u'rskorean'),
 ('unihan', u'rsunicode'),
 ('unihan', u'sbgy'),
 ('unihan', u'semanticvariant'),
 ('unihan', u'simplifiedvariant'),
 ('unihan', u'specializedsemanticvariant'),
 ('unihan', u'taiwantelegraph'),
 ('unihan', u'tang'),
 ('unihan', u'totalstrokes'),
 ('unihan', u'traditionalvariant'),
 ('unihan', u'vietnamese'),
 ('unihan', u'xerox'),
 ('unihan', u'xhc1983'),
 ('unihan', u'zvariant')]
