DReadablePropertyKeys = {
    'ccdict.cantonese': 'Cantonese Readings',
    'ccdict.english': 'English Definition',
    'ccdict.hakka': 'Hakka Readings',
    'ccdict.mandarin': 'Mandarin Readings',
    'ccdict.r/s': '{{FIXME}} Radicals and Additional Strokes',
    'kanjidic.dicref_crowley': '',
    'kanjidic.dicref_gakken': '',
    'kanjidic.dicref_halpern_kkld': '',
    'kanjidic.dicref_halpern_njecd': '',
    'kanjidic.dicref_heisig': '',
    'kanjidic.dicref_henshall': '',
    'kanjidic.dicref_henshall3': '',
    'kanjidic.dicref_jf_cards': '',
    'kanjidic.dicref_kanji_in_context': '',
    'kanjidic.dicref_kodansha_compact': '',
    'kanjidic.dicref_maniette': '',
    'kanjidic.dicref_moro': '',
    'kanjidic.dicref_nelson_c': '',
    'kanjidic.dicref_nelson_n': '',
    'kanjidic.dicref_oneill_kk': '',
    'kanjidic.dicref_oneill_names': '',
    'kanjidic.dicref_sakade': '',
    'kanjidic.dicref_sh_kk': '',
    'kanjidic.dicref_tutt_cards': '',
    'kanjidic.freq': 'Japanese Frequency',
    'kanjidic.grade': 'Japanese Grade',
    'kanjidic.jlpt': 'Japanese JLPT level',
    'kanjidic.meaning': 'English Definition for Japanese',
    'kanjidic.meaning_es': 'Spanish Definition for Japanese',
    'kanjidic.meaning_fr': 'French Definition for Japanese',
    'kanjidic.meaning_pt': 'Portuguese Definition for Japanese',
    'kanjidic.querycode_deroo': '',
    'kanjidic.rad_classical': '',
    'kanjidic.rad_name': '',
    'kanjidic.rad_nelson_c': '',
    'kanjidic.reading_ja_kun': 'Kun Readings',
    'kanjidic.reading_ja_on': 'On Readings',
    'kanjidic.reading_korean_h': 'Korean Hangul Readings',
    'kanjidic.reading_korean_r': 'Korean Romanised Readings',
    'kanjidic.reading_nanori': 'Japanese Nanori Readings',
    'kanjidic.reading_pinyin': 'Mandarin Readings',
    'kanjidic.stroke_count': 'Japanese Number of Strokes',
    'nameslist.see also': '',
    'nameslist.subblock see also': '',
    'unicodedata.age': 'Unicode Age',
    'unicodedata.also called': 'Also Called',
    'unicodedata.arabic shaping group': 'Arabic Shaping Group',
    'unicodedata.arabic shaping type': 'Arabic Shaping Type',
    'unicodedata.bidirectional category': 'Bidirectional Category',
    'unicodedata.block': 'General Block',
    'unicodedata.canonical combining classes': '',
    'unicodedata.case folding status': '',
    'unicodedata.comments': '',
    'unicodedata.conscript blocks': '',
    'unicodedata.conscript name': '',
    'unicodedata.core properties': '',
    'unicodedata.decimal digit value': '',
    'unicodedata.digit value': '',
    'unicodedata.east asian width': '',
    'unicodedata.fc nfkc closure': '',
    'unicodedata.formally also called': '',
    'unicodedata.general category': '',
    'unicodedata.grapheme break': '',
    'unicodedata.joining type': '',
    'unicodedata.line break': '',
    'unicodedata.name': '',
    'unicodedata.named aliases': '',
    'unicodedata.numeric value': '',
    'unicodedata.property list': '',
    'unicodedata.script': '',
    'unicodedata.sentence break': '',
    'unicodedata.technical notice': '',
    'unicodedata.unicode 1.0 name': '',
    'unicodedata.word break': '',
    'unihan.accountingnumeric': '',
    'unihan.cantonese': '',
    'unihan.cheungbauerindex': '',
    'unihan.cihait': '',
    'unihan.cowles': '',
    'unihan.daejaweon': '',
    'unihan.definition': 'English Definition',
    'unihan.fennindex': '',
    'unihan.frequency': 'Chinese Frequency',
    'unihan.gradelevel': 'Chinese Grade Level',
    'unihan.gsr': '',
    'unihan.hangul': 'Korean Hangul Readings',
    'unihan.hanyu': '',
    'unihan.hanyupinlu': '',
    'unihan.hanyupinyin': 'Mandarin Hanyu Pinyin', # ???
    'unihan.hkglyph': '',
    'unihan.iicore': '',
    'unihan.japanesekun': 'Japanese Kun',
    'unihan.japaneseon': 'Japanese On',
    'unihan.kangxi': 'Kangxi Radical',
    'unihan.karlgren': '',
    'unihan.korean': 'Korean Romanised Readings',
    'unihan.lau': '',
    'unihan.mandarin': 'Mandarin Readings',
    'unihan.matthews': '',
    'unihan.meyerwempe': '',
    'unihan.morohashi': '',
    'unihan.nelson': '',

    'unihan.sbgy': '',
    'unihan.tang': 'Tang Dynasty Chinese Readings',
    'unihan.totalstrokes': 'Total Strokes',
    'unihan.vietnamese': 'Vietnamese Readings',
    'unihan.xhc1983': '',
}


CAT_RS = 1
CAT_READINGS = 2
CAT_DEFINITIONS = 4
CAT_CROSS_REF = 8
CAT_VARIANTS = 16
CAT_INPUT_CODE = 32
CAT_CASING = 64
CAT_IRG_MAPPING = 128



class KeyValue:
    def __init__(self, cat, name, desc=None, LISOs=None, ignored=False):
        self.cat = cat
        self.name = name
        self.desc = desc
        self.ignored = ignored

    def set_property_key(self, pk):
        pass


kv = KeyValue


char_data.kanjidic.freq['c']

list(char_data.unihan.keys())
char_data.unihan.freq['c']
list(char_data.unihan.freq.keys())
char_data.unihan.freq.search(500)


DReadablePropertyKeys2 = {
    'ccdict.big5': '',
    'ccdict.cangjie': '',
    'ccdict.cantonese': 'Cantonese Jyutping Readings',
    'ccdict.cns11643': '',
    'ccdict.english': 'English Definition',
    'ccdict.fourcorner': 'Four Corner Input Code',
    'ccdict.gb': '',
    'ccdict.hakka': 'Hakka Readings',
    'ccdict.mandarin': 'Mandarin Readings',
    'ccdict.r/s': 'Chinese Radical and Additional Strokes',
    'ccdict.totalstrokes': '',
    'ccdict.utf8': '',
    'hanzi variants.abbreviated form': '',
    'hanzi variants.antonym': '',
    'hanzi variants.archaic form': '',
    'hanzi variants.archaic variant': '',
    'hanzi variants.chinese classifier': '',
    'hanzi variants.chinesetraditional': '',
    'hanzi variants.correct form': '',
    'hanzi variants.erhua variant': '',
    'hanzi variants.erroneous form': '',
    'hanzi variants.japanese variant': '',
    'hanzi variants.japanesesimplified': '',
    'hanzi variants.less common variant': '',
    'hanzi variants.modern form': '',
    'hanzi variants.modern variant': '',
    'hanzi variants.more common variant': '',
    'hanzi variants.non-erhua variant': '',
    'hanzi variants.non-japanese variant': '',
    'hanzi variants.non-prc variant': '',
    'hanzi variants.obscure variant': '',
    'hanzi variants.other variant': '',
    'hanzi variants.popular variant': '',
    'hanzi variants.prc variant': '',
    'hanzi variants.same as': '',
    'hanzi variants.see also': '',
    'hanzi variants.unabbreviated form': '',
    'hanzi variants.variant of': '',
    'hanzi variants.words which can use classifier': '',
    'kanjidic.crossref_deroo': '',
    'kanjidic.crossref_jis208': '',
    'kanjidic.crossref_jis212': '',
    'kanjidic.crossref_jis213': '',
    'kanjidic.crossref_nelson_c': '',
    'kanjidic.crossref_njecd': '',
    'kanjidic.crossref_oneill': '',
    'kanjidic.crossref_s_h': '',
    'kanjidic.crossref_ucs': '',
    'kanjidic.dicref_busy_people': '',
    'kanjidic.dicref_crowley': '',
    'kanjidic.dicref_gakken': '',
    'kanjidic.dicref_halpern_kkld': '',
    'kanjidic.dicref_halpern_njecd': '',
    'kanjidic.dicref_heisig': '',
    'kanjidic.dicref_henshall': '',
    'kanjidic.dicref_henshall3': '',
    'kanjidic.dicref_jf_cards': '',
    'kanjidic.dicref_kanji_in_context': '',
    'kanjidic.dicref_kodansha_compact': '',
    'kanjidic.dicref_maniette': '',
    'kanjidic.dicref_moro': '',
    'kanjidic.dicref_nelson_c': '',
    'kanjidic.dicref_nelson_n': '',
    'kanjidic.dicref_oneill_kk': '',
    'kanjidic.dicref_oneill_names': '',
    'kanjidic.dicref_sakade': '',
    'kanjidic.dicref_sh_kk': '',
    'kanjidic.dicref_tutt_cards': '',
    'kanjidic.freq': 'Japanese Frequency',
    'kanjidic.grade': 'Japanese Grade',
    'kanjidic.jlpt': 'Japanese JLPT level',
    'kanjidic.meaning': 'English Definition for Japanese',
    'kanjidic.meaning_es': 'Spanish Definition for Japanese',
    'kanjidic.meaning_fr': 'French Definition for Japanese',
    'kanjidic.meaning_pt': 'Portuguese Definition for Japanese',
    'kanjidic.querycode_deroo': '',
    'kanjidic.querycode_four_corner': '',
    'kanjidic.querycode_sh_desc': '',
    'kanjidic.rad_classical': '',
    'kanjidic.rad_name': '',
    'kanjidic.rad_nelson_c': '',
    'kanjidic.reading_ja_kun': '',
    'kanjidic.reading_ja_on': '',
    'kanjidic.reading_korean_h': '',
    'kanjidic.reading_korean_r': '',
    'kanjidic.reading_nanori': '',
    'kanjidic.reading_pinyin': '',
    'kanjidic.stroke_count': '',
    'nameslist.also called': '',
    'nameslist.block description': '',
    'nameslist.block name': '',
    'nameslist.comments': '',
    'nameslist.formally also called': '',
    'nameslist.has separator': '',
    'nameslist.see also': '',
    'nameslist.subblock heading': '',
    'nameslist.subblock see also': '',
    'nameslist.subblock technical notice': '',
    'nameslist.technical notice': '',
    'unicodedata.age': '',
    'unicodedata.also called': '',
    'unicodedata.arabic shaping group': '',
    'unicodedata.arabic shaping type': '',
    'unicodedata.bidi mirroring': '',
    'unicodedata.bidirectional category': '',
    'unicodedata.block': '',
    'unicodedata.block description': '',
    'unicodedata.block name': '',
    'unicodedata.canonical combining classes': '',
    'unicodedata.case folding': '',
    'unicodedata.case folding status': '',
    'unicodedata.changes when nfkc casefolded': '',
    'unicodedata.comments': '',
    'unicodedata.compatibility mapping': '',
    'unicodedata.composition exclusions': '',
    'unicodedata.conscript blocks': '',
    'unicodedata.conscript name': '',
    'unicodedata.core properties': '',
    'unicodedata.decimal digit value': '',
    'unicodedata.decomposed form': '',
    'unicodedata.digit value': '',
    'unicodedata.east asian width': '',
    'unicodedata.expands on nfc': '',
    'unicodedata.expands on nfd': '',
    'unicodedata.expands on nfkc': '',
    'unicodedata.expands on nfkd': '',
    'unicodedata.fc nfkc closure': '',
    'unicodedata.formally also called': '',
    'unicodedata.full composition exclusion': '',
    'unicodedata.general category': '',
    'unicodedata.grapheme break': '',
    'unicodedata.joining type': '',
    'unicodedata.line break': '',
    'unicodedata.lowercase': '',
    'unicodedata.mirrored': '',
    'unicodedata.name': '',
    'unicodedata.named aliases': '',
    'unicodedata.nfc quick check': '',
    'unicodedata.nfd quick check': '',
    'unicodedata.nfkc casefold': '',
    'unicodedata.nfkc quick check': '',
    'unicodedata.nfkd quick check': '',
    'unicodedata.normalization corrections corrected': '',
    'unicodedata.normalization corrections errors': '',
    'unicodedata.numeric value': '',
    'unicodedata.property list': '',
    'unicodedata.script': '',
    'unicodedata.see also': '',
    'unicodedata.sentence break': '',
    'unicodedata.special casing condition list': '',
    'unicodedata.special casing lower': '',
    'unicodedata.special casing title': '',
    'unicodedata.special casing upper': '',
    'unicodedata.subblock heading': '',
    'unicodedata.subblock see also': '',
    'unicodedata.subblock technical notice': '',
    'unicodedata.technical notice': '',
    'unicodedata.titlecase': '',
    'unicodedata.unicode 1.0 name': '',
    'unicodedata.uppercase': '',
    'unicodedata.word break': '',
    'unihan.accountingnumeric': '',
    'unihan.bigfive': '',
    'unihan.cangjie': '',
    'unihan.cantonese': '',
    'unihan.cccii': '',
    'unihan.cheungbauer': '',
    'unihan.cheungbauerindex': '',
    'unihan.cihait': '',
    'unihan.cns1986': '',
    'unihan.cns1992': '',
    'unihan.compatibilityvariant': '',
    'unihan.cowles': '',
    'unihan.daejaweon': '',
    'unihan.definition': '',
    'unihan.eacc': '',
    'unihan.fenn': '',
    'unihan.fennindex': '',
    'unihan.fourcornercode': '',
    'unihan.frequency': '',
    'unihan.gb0': '',
    'unihan.gb1': '',
    'unihan.gb3': '',
    'unihan.gb5': '',
    'unihan.gb7': '',
    'unihan.gb8': '',
    'unihan.gradelevel': '',
    'unihan.gsr': '',
    'unihan.hangul': '',
    'unihan.hanyu': '',
    'unihan.hanyupinlu': '',
    'unihan.hanyupinyin': '',
    'unihan.hdzradbreak': '',
    'unihan.hkglyph': '',
    'unihan.hkscs': '',
    'unihan.ibmjapan': '',
    'unihan.iicore': '',
    'unihan.irg_gsource': kv(CAT_IRG_MAPPING, 'IRG G Source'),
    'unihan.irg_hsource': kv('IRG H Source'),
    'unihan.irg_jsource': kv('IRG J Source'),
    'unihan.irg_kpsource': kv('IRG KP Source'),
    'unihan.irg_ksource': kv('IRG K Source'),
    'unihan.irg_msource': kv('IRG M Source'),
    'unihan.irg_tsource': kv('IRG T Source'),
    'unihan.irg_usource': kv('IRG U Source'),
    'unihan.irg_vsource': kv('IRG V Source'),
    'unihan.irgdaejaweon': kv('IRG Dae Jaweon'),
    'unihan.irgdaikanwaziten': kv('IRG Dai Kanwa Ziten'),
    'unihan.irghanyudazidian': kv('IRG Hanyu Da Zidian'),
    'unihan.irgkangxi': kv('IRG Kangxi'),
    'unihan.japanesekun': kv('Japanese Romanised Kun'),
    'unihan.japaneseon': kv('Japanese Romansed On'),
    'unihan.jis0': kv('JIS 0', ignored=True),
    'unihan.jis0213': kv('JIS 0213', ignored=True),
    'unihan.jis1': kv('JIS 1', ignored=True),
    'unihan.kangxi': '',
    'unihan.karlgren': '',
    'unihan.korean': '',
    'unihan.kps0': '',
    'unihan.kps1': '',
    'unihan.ksc0': '',
    'unihan.ksc1': '',
    'unihan.lau': '',
    'unihan.mainlandtelegraph': '',
    'unihan.mandarin': '',
    'unihan.matthews': '',
    'unihan.meyerwempe': '',
    'unihan.morohashi': '',
    'unihan.nelson': '',
    'unihan.othernumeric': 'Other Numeric Value',
    'unihan.phonetic': '',
    'unihan.primarynumeric': 'Primary Numeric Value',
    'unihan.pseudogb1': '',
    'unihan.rsadobe_japan1_6': '',
    'unihan.rsjapanese': 'Japanese Radicals and Additional Strokes',
    'unihan.rskangxi': 'Kangxi Radicals and Additional Strokes',
    'unihan.rskanwa': 'Kanwa Radicals and Additional Strokes',
    'unihan.rskorean': 'Korean Radicals and Additional Strokes',
    'unihan.rsunicode': 'Unicode Radicals and Additional Strokes',
    'unihan.sbgy': '',
    'unihan.semanticvariant': '',
    'unihan.simplifiedvariant': '',
    'unihan.specializedsemanticvariant': '',
    'unihan.taiwantelegraph': '',
    'unihan.tang': '',
    'unihan.totalstrokes': '',
    'unihan.traditionalvariant': '',
    'unihan.vietnamese': '',
    'unihan.xerox': '',
    'unihan.xhc1983': '',
    'unihan.zvariant': ''
}

