DEnum = {
    "IICore": {
        "False": "No, not commonly used in East Asia",
        "None": "None",
        "True": "Yes, commonly used in East Asia"
    },
    "age": {
        "1.1": "Unicode 1.1.0 June 1993",
        "2.0": "Unicode 2.0.0 July 1996",
        "2.1": "Unicode 2.1.2 May 1998",
        "3.0": "Unicode 3.0.0 September 1999",
        "3.1": "Unicode 3.1.0 March 2001",
        "3.2": "Unicode 3.2.0 March 2002",
        "4.0": "Unicode 4.0.0 April 2003",
        "4.1": "Unicode 4.1.0 March 2005",
        "5.0": "Unicode 5.0.0 July 2006",
        "5.1": "Unicode 5.1.0 April 2008",
        "5.2": "Unicode 5.2.0 October 2009",
        "6.0": "Unicode 6.0.0 October 2010",
        "6.1": "Unicode 6.1.0 January 2012",
        "None": "Unassigned"
    },
    "arabic shaping group": {
        "AIN": "Arabic Ain",
        "ALAPH": "Syriac Alaph",
        "ALEF": "Arabic Alef",
        "BEH": "Arabic Beh",
        "BETH": "Syriac Beth",
        "BURUSHASKI YEH BARREE": "Arabic Burushaski Yeh Barree",
        "C": "Join Causing",
        "D": "Dual Joining",
        "DAL": "Arabic Dal",
        "DALATH RISH": "Syriac Dalath Rish",
        "E": "Syriac E",
        "FARSI YEH": "Farsi Yeh",
        "FE": "Syriac Fe",
        "FEH": "Arabic Feh",
        "FINAL SEMKATH": "Syriac Final Semkath",
        "GAF": "Arabic Gaf",
        "GAMAL": "Syriac Gamal",
        "HAH": "Arabic Hah",
        "HE": "Syriac He",
        "HEH": "Arabic Heh",
        "HEH GOAL": "Arabic Heh Goal",
        "HETH": "Syriac Heth",
        "KAF": "Arabic Kaf",
        "KAPH": "Syriac Kaph",
        "KHAPH": "Syriac Khaph",
        "KNOTTED HEH": "Arabic Knotted Heh",
        "L": "Left Joining",
        "LAM": "Arabic Lam",
        "LAMADH": "Syriac Lamadh",
        "MEEM": "Arabic Meem",
        "MIM": "Syriac Mim",
        "NOON": "Arabic Noon",
        "NUN": "Syriac Nun",
        "NYA": "Arabic Nya",
        "No_Joining_Group": "No Joining Group",
        "None": "Unknown",
        "PE": "Syriac Pe",
        "QAF": "Arabic Qaf",
        "QAPH": "Syriac Qaph",
        "R": "Right Joining",
        "REH": "Arabic Reh",
        "REVERSED PE": "Syriac Reversed Pe",
        "SAD": "Arabic Sad",
        "SADHE": "Syriac Sadhe",
        "SEEN": "Arabic Seen",
        "SEMKATH": "Syriac Semkath",
        "SHIN": "Syriac Shin",
        "SWASH KAF": "Arabic Swash Kaf",
        "SYRIAC WAW": "Syriac Waw",
        "T": "Transparent",
        "TAH": "Arabic Tah",
        "TAW": "Syriac Taw",
        "TEH MARBUTA": "Arabic Teh Marbuta",
        "TEH MARBUTA GOAL": "Arabic Teh Marbuta Goal",
        "TETH": "Syriac Teth",
        "U": "Non Joining",
        "WAW": "Arabic Waw",
        "YEH": "Arabic Yeh",
        "YEH BARREE": "Arabic Yeh Baree",
        "YEH WITH TAIL": "Arabic Yeh With Tail",
        "YUDH": "Syriac Yudh",
        "YUDH HE": "Syriac Yudh He",
        "ZAIN": "Syriac Zain",
        "ZHAIN": "Syriac Zhain"
    },
    "arabic shaping type": {
        "C": "Join Causing",
        "D": "Dual Joining",
        "L": "Left Joining",
        "None": "Unknown",
        "R": "Right Joining",
        "T": "Transparent",
        "U": "Non Joining"
    },
    "bidirectional category": {
        "AL": "Right-to-Left Arabic",
        "AN": "Arabic Number",
        "B": "Paragraph Separator",
        "BN": "Boundary Neutral",
        "CS": "Common Number Separator",
        "EN": "European Number",
        "ES": "European Number Separator",
        "ET": "European Number Terminator",
        "L": "Left-to-Right",
        "LRE": "Left-to-Right Embedding",
        "LRO": "Left-to-Right Override",
        "NSM": "Non-Spacing Mark",
        "None": "Unknown",
        "ON": "Other Neutrals",
        "PDF": "Pop Directional Format",
        "R": "Right-to-Left",
        "RLE": "Right-to-Left Embedding",
        "RLO": "Right-to-Left Override",
        "S": "Segment Separator",
        "WS": "Whitespace"
    },
    "canonical combining classes": {
        "0": "Spacing, split, enclosing, reordrant, and Tibetan subjoined",
        "1": "Overlays and interior",
        "10": "fixed position class 10",
        "100": "fixed position class 100",
        "101": "fixed position class 101",
        "102": "fixed position class 102",
        "103": "fixed position class 103",
        "104": "fixed position class 104",
        "105": "fixed position class 105",
        "106": "fixed position class 106",
        "107": "fixed position class 107",
        "108": "fixed position class 108",
        "109": "fixed position class 109",
        "11": "fixed position class 11",
        "110": "fixed position class 110",
        "111": "fixed position class 111",
        "112": "fixed position class 112",
        "113": "fixed position class 113",
        "114": "fixed position class 114",
        "115": "fixed position class 115",
        "116": "fixed position class 116",
        "117": "fixed position class 117",
        "118": "fixed position class 118",
        "119": "fixed position class 119",
        "12": "fixed position class 12",
        "120": "fixed position class 120",
        "121": "fixed position class 121",
        "122": "fixed position class 122",
        "123": "fixed position class 123",
        "124": "fixed position class 124",
        "125": "fixed position class 125",
        "126": "fixed position class 126",
        "127": "fixed position class 127",
        "128": "fixed position class 128",
        "129": "fixed position class 129",
        "13": "fixed position class 13",
        "130": "fixed position class 130",
        "131": "fixed position class 131",
        "132": "fixed position class 132",
        "133": "fixed position class 133",
        "134": "fixed position class 134",
        "135": "fixed position class 135",
        "136": "fixed position class 136",
        "137": "fixed position class 137",
        "138": "fixed position class 138",
        "139": "fixed position class 139",
        "14": "fixed position class 14",
        "140": "fixed position class 140",
        "141": "fixed position class 141",
        "142": "fixed position class 142",
        "143": "fixed position class 143",
        "144": "fixed position class 144",
        "145": "fixed position class 145",
        "146": "fixed position class 146",
        "147": "fixed position class 147",
        "148": "fixed position class 148",
        "149": "fixed position class 149",
        "15": "fixed position class 15",
        "150": "fixed position class 150",
        "151": "fixed position class 151",
        "152": "fixed position class 152",
        "153": "fixed position class 153",
        "154": "fixed position class 154",
        "155": "fixed position class 155",
        "156": "fixed position class 156",
        "157": "fixed position class 157",
        "158": "fixed position class 158",
        "159": "fixed position class 159",
        "16": "fixed position class 16",
        "160": "fixed position class 160",
        "161": "fixed position class 161",
        "162": "fixed position class 162",
        "163": "fixed position class 163",
        "164": "fixed position class 164",
        "165": "fixed position class 165",
        "166": "fixed position class 166",
        "167": "fixed position class 167",
        "168": "fixed position class 168",
        "169": "fixed position class 169",
        "17": "fixed position class 17",
        "170": "fixed position class 170",
        "171": "fixed position class 171",
        "172": "fixed position class 172",
        "173": "fixed position class 173",
        "174": "fixed position class 174",
        "175": "fixed position class 175",
        "176": "fixed position class 176",
        "177": "fixed position class 177",
        "178": "fixed position class 178",
        "179": "fixed position class 179",
        "18": "fixed position class 18",
        "180": "fixed position class 180",
        "181": "fixed position class 181",
        "182": "fixed position class 182",
        "183": "fixed position class 183",
        "184": "fixed position class 184",
        "185": "fixed position class 185",
        "186": "fixed position class 186",
        "187": "fixed position class 187",
        "188": "fixed position class 188",
        "189": "fixed position class 189",
        "19": "fixed position class 19",
        "190": "fixed position class 190",
        "191": "fixed position class 191",
        "192": "fixed position class 192",
        "193": "fixed position class 193",
        "194": "fixed position class 194",
        "195": "fixed position class 195",
        "196": "fixed position class 196",
        "197": "fixed position class 197",
        "198": "fixed position class 198",
        "199": "fixed position class 199",
        "20": "fixed position class 20",
        "200": "Below left attached",
        "202": "Below attached",
        "204": "Below right attached",
        "208": "Left attached (reordrant around single base character)",
        "21": "fixed position class 21",
        "210": "Right attached",
        "212": "Above left attached",
        "214": "Above attached",
        "216": "Above right attached",
        "218": "Below left",
        "22": "fixed position class 22",
        "220": "Below",
        "222": "Below right",
        "224": "Left (reordrant around single base character)",
        "226": "Right",
        "228": "Above left",
        "23": "fixed position class 23",
        "230": "Above",
        "232": "Above right",
        "233": "Double below",
        "234": "Double above",
        "24": "fixed position class 24",
        "240": "Below (iota subscript)",
        "25": "fixed position class 25",
        "26": "fixed position class 26",
        "27": "fixed position class 27",
        "28": "fixed position class 28",
        "29": "fixed position class 29",
        "30": "fixed position class 30",
        "31": "fixed position class 31",
        "32": "fixed position class 32",
        "33": "fixed position class 33",
        "34": "fixed position class 34",
        "35": "fixed position class 35",
        "36": "fixed position class 36",
        "37": "fixed position class 37",
        "38": "fixed position class 38",
        "39": "fixed position class 39",
        "40": "fixed position class 40",
        "41": "fixed position class 41",
        "42": "fixed position class 42",
        "43": "fixed position class 43",
        "44": "fixed position class 44",
        "45": "fixed position class 45",
        "46": "fixed position class 46",
        "47": "fixed position class 47",
        "48": "fixed position class 48",
        "49": "fixed position class 49",
        "50": "fixed position class 50",
        "51": "fixed position class 51",
        "52": "fixed position class 52",
        "53": "fixed position class 53",
        "54": "fixed position class 54",
        "55": "fixed position class 55",
        "56": "fixed position class 56",
        "57": "fixed position class 57",
        "58": "fixed position class 58",
        "59": "fixed position class 59",
        "60": "fixed position class 60",
        "61": "fixed position class 61",
        "62": "fixed position class 62",
        "63": "fixed position class 63",
        "64": "fixed position class 64",
        "65": "fixed position class 65",
        "66": "fixed position class 66",
        "67": "fixed position class 67",
        "68": "fixed position class 68",
        "69": "fixed position class 69",
        "7": "Nuktas",
        "70": "fixed position class 70",
        "71": "fixed position class 71",
        "72": "fixed position class 72",
        "73": "fixed position class 73",
        "74": "fixed position class 74",
        "75": "fixed position class 75",
        "76": "fixed position class 76",
        "77": "fixed position class 77",
        "78": "fixed position class 78",
        "79": "fixed position class 79",
        "8": "Hiragana/Katakana voicing marks",
        "80": "fixed position class 80",
        "81": "fixed position class 81",
        "82": "fixed position class 82",
        "83": "fixed position class 83",
        "84": "fixed position class 84",
        "85": "fixed position class 85",
        "86": "fixed position class 86",
        "87": "fixed position class 87",
        "88": "fixed position class 88",
        "89": "fixed position class 89",
        "9": "Viramas",
        "90": "fixed position class 90",
        "91": "fixed position class 91",
        "92": "fixed position class 92",
        "93": "fixed position class 93",
        "94": "fixed position class 94",
        "95": "fixed position class 95",
        "96": "fixed position class 96",
        "97": "fixed position class 97",
        "98": "fixed position class 98",
        "99": "fixed position class 99",
        "None": "Unknown"
    },
    "case folding status": {
        "C": "Common Case Folding",
        "F": "Full Case Folding",
        "None": "None",
        "S": "Simple Case Folding",
        "T": "Special Case"
    },
    "character decomposition mapping": {
        "<circle>": "An encircled form.",
        "<compat>": "Otherwise unspecified compatibility character.",
        "<final>": "A final presentation form (Arabic).",
        "<font>": "A font variant (e.g. a blackletter form).",
        "<fraction>": "A vulgar fraction form.",
        "<initial>": "An initial presentation form (Arabic).",
        "<isolated>": "An isolated presentation form (Arabic).",
        "<medial>": "A medial presentation form (Arabic).",
        "<narrow>": "A narrow (or hankaku) compatibility character.",
        "<noBreak>": "A no-break version of a space or hyphen.",
        "<small>": "A small variant form (CNS compatibility).",
        "<square>": "A CJK squared font variant.",
        "<sub>": "A subscript form.",
        "<super>": "A superscript form.",
        "<vertical>": "A vertical layout presentation form.",
        "<wide>": "A wide (or zenkaku) compatibility character.",
        "None": "Unknown"
    },
    "composition exclusions": {
        "False": "None",
        "None": "None",
        "True": "Excluded from Compositions"
    },
    "east asian width": {
        "A": "Ambiguous (Sometimes Wide and Sometimes Narrow)",
        "F": "Fullwidth",
        "H": "Halfwidth",
        "N": "Neutral (Not East Asian)",
        "Na": "Always Narrow",
        "None": "Neutral (Not East Asian)",
        "W": "Always Wide"
    },
    "general category": {
        "Cc": "Control Other",
        "Cf": "Format Other",
        "Cn": "Not Assigned (no characters in the file have this property) Other",
        "Co": "Private Use Other",
        "Cs": "Surrogate Other",
        "Ll": "Lowercase Letter",
        "Lm": "Modifier Letter",
        "Lo": "Other Letter",
        "Lt": "Titlecase Letter",
        "Lu": "Uppercase Letter",
        "Mc": "Spacing Combining Mark",
        "Me": "Enclosing Mark",
        "Mn": "Nonspacing Mark",
        "Nd": "Decimal Digit Number",
        "Nl": "Letter Number",
        "No": "Other Number",
        "None": "Unknown",
        "Pc": "Connector Punctuation",
        "Pd": "Dash Punctuation",
        "Pe": "Close Punctuation",
        "Pf": "Final Quote (may behave like Ps or Pe depending on usage) Punctuation",
        "Pi": "Initial Quote (may behave like Ps or Pe depending on usage) Punctuation",
        "Po": "Other Punctuation",
        "Ps": "Open Punctuation",
        "Sc": "Currency Symbol",
        "Sk": "Modifier Symbol",
        "Sm": "Math Symbol",
        "So": "Other Symbol",
        "Zl": "Line Separator",
        "Zp": "Paragraph Separator",
        "Zs": "Space Separator"
    },
    "grapheme break": {
        "Any": "Any Character",
        "CR": "Carriage Return (CR)",
        "Control": "Control",
        "Extend": "Grapheme Extended",
        "L": "Hangul Syllable Type L",
        "LF": "Line Feed (LF)",
        "LV": "Hangul Syllable Type LV",
        "LVT": "Hangul Syllable Type LVT",
        "None": "Unknown",
        "Prepend": "Prepend",
        "SpacingMark": "Spacing Mark",
        "T": "Hangul Syllable Type T",
        "V": "Hangul Syllable Type V"
    },
    "joining type": {
        "C": "Join Causing",
        "D": "Dual Joining",
        "None": "Unknown",
        "R": "Right Joining",
        "T": "Transparent"
    },
    "line break": {
        "AI": "Ambiguous",
        "AL": "Ordinary Alphabetic and Symbol Characters",
        "B2": "Break Opportunity Before and After",
        "BA": "Break Opportunity After",
        "BB": "Break Opportunity Before",
        "BK": "Mandatory Break",
        "CB": "Contingent Break Opportunity",
        "CL": "Closing Punctuation",
        "CM": "Attached Characters and Combining Marks",
        "CP": "Close Parenthesis",
        "CR": "Carriage Return",
        "EX": "Exclamation/Interrogation",
        "GL": "Non-breaking (\"Glue\")",
        "H2": "Hangul LV Syllable",
        "H3": "Hangul LVT Syllable",
        "HL": "Hebrew Letter",
        "HY": "Hyphen",
        "ID": "Ideographic",
        "IN": "Inseparable",
        "IS": "Infix Separator (Numeric)",
        "JL": "Hangul L Jamo",
        "JT": "Hangul T Jamo",
        "JV": "Hangul V Jamo",
        "LF": "Line Feed",
        "NL": "Next Line",
        "NS": "Nonstarter",
        "NU": "Numeric",
        "None": "Unknown",
        "OP": "Opening Punctuation",
        "PO": "Postfix (Numeric)",
        "PR": "Prefix (Numeric)",
        "QU": "Ambiguous Quotation",
        "SA": "Complex Context Dependent (South East Asian)",
        "SG": "Surrogates",
        "SP": "Space",
        "SY": "Symbols Allowing Break After",
        "WJ": "Word Joiner",
        "XX": "Unknown",
        "ZW": "Zero Width Space"
    },
    "mirrored": {
        "N": "No (Not Flipped on Right-to-Left)",
        "None": "Unknown",
        "Y": "Yes (Flipped on Right-to-Left)"
    },
    "sentence break": {
        "ATerm": "Alphabetic Terminator (Full Stop)",
        "Any": "Any Character",
        "CR": "Carriage Return",
        "Close": "Close",
        "Extend": "Grapheme Extend",
        "Format": "Format (without ZWJ/ZWNJ)",
        "LF": "Line Feed",
        "Lower": "Lowercase",
        "None": "Unknown",
        "Numeric": "Numeric",
        "OLetter": "Other Letter",
        "SContinue": "Sentence Continue",
        "STerm": "Space Terminator",
        "Sep": "Separator",
        "Sp": "Space",
        "Upper": "Uppercase"
    },
    "word break": {
        "ALetter": "Alphabetic Letter",
        "Any": "Any Character",
        "CR": "Carriage Return",
        "Extend": "Grapheme Extend",
        "ExtendNumLet": "Connector Punctuation",
        "Format": "General Format Property",
        "Katakana": "Katakana",
        "LF": "Line Feed",
        "MidLetter": "Middle Letter",
        "MidNum": "Middle Number",
        "MidNumLet": "Middle Numeric Letter",
        "Newline": "Newline",
        "None": "Unknown",
        "Numeric": "Numeric"
    }
}
